### PR TITLE
Edit button styles

### PR DESCRIPTION
**Pull request by AshtrayShetty**
There are also some features (if you would like) that I added, such as once you complete a task you can't revert back the checked box (it stays checked) and you can't edit this task. I thought this would fit because once a task is finished, you can't go back on it (Why would you?). Anyway, as for the edit button highlight thing, I tried doing some digging and found out that there is a way (by `import {Ripple} from 'rmwc'`. You can find the [demo](https://codesandbox.io/s/2xp677qxyy) here. I hope you figure out a solution :wink:

### CODE REVIEW

**Comment by neelkamath** [comment]
I'd rather allow the user to be able to edit completed tasks. They might later want to modify their plan, or they might have accidentally marked something as complete.

**Comment by AshtrayShetty** [comment]
Oh okay! One more thing (feature) I would like (maybe to work on) is after the end of the reserve time, all the tasks get cleared out (new day, new start). Or maybe just the completed tasks get cleared.

**Comment by neelkamath** [comment]
There is a clear button which allows you to delete all the tasks listed. I wouldn't want the tasks automatically getting deleted because the user may have accidentally set an incorrect day end (e.g., when switching between AM and PM), and also we'd have to tell them that we purposefully deleted the data (which is no faster than having them do it manually when they actually want to).

As for your second suggestion, which I understood as allowing only the clearing of completed tasks, that sounds good. Perhaps when the user clicks "clear", the dialog will have two buttons instead of one. Currently, there is only one button which is meant as a confirmation for the bulk delete. Instead, we could have one button for confirming a bulk delete, and another for confirming a bulk delete for only completed tasks.

**Comment by neelkamath** [comment]
https://imgur.com/a/7II8HYR

When I run your changes, the edit icon doesn't seem to be vertically centered.

**Comment by AshtrayShetty** [comment]
I'll look into it.

**Comment by AshtrayShetty** [comment]
I got it done (vertically center edit icon). It was a bootstrap fix lmao.

**Comment by neelkamath** [comment]
It looks like [this](https://imgur.com/a/FJkhqXJ) for me. Unless you're getting a different output, I think you've misunderstood the requirement. I suppose I should have given a clearer design.

So basically the way that the task's duration on the right is vertically centered ([screenshot](https://imgur.com/a/eWMt2UF)), I want the checkbox and edit icons to be vertically centered. They should still be right next to each other as they are currently. It's just that they should automatically move down along with the task according to the length of the task's text.

**Comment by AshtrayShetty** [comment]
I think it's cause you changed the StyledButton style (margin-top: 0.25em;)
Edit button styles by AshtrayShetty · Pull Request #16 · neelkamath_time-bend-web - Google Chrome 17-03-2020 20_00_51

**Comment by neelkamath** [comment]
Ah, I must've considered them similar enough to merge whilst resolving merge conflicts. Do you mind adding a commit to revert that?

**Comment by AshtrayShetty** [comment]
Sure thing lad!

**Comment by neelkamath** [comment]
Can you please merge https://github.com/AshtrayShetty/time-bend-web/pull/1?

**Pull request merged**
