### PR TITLE
Styles

### PR DESCRIPTION
**Pull request by AshtrayShetty**
Because the button positions were messed up (again)

### CODE REVIEW

**Comment by neelkamath** [comment]
I reverted your changes because it broke the production build. But not to worry, the checkbox and edit icons are still vertically centered (thanks to you).

I'm not sure which styles have been broken. Can you show a before/after screenshot? Remember to use incognito mode when viewing the production site (http://time-bend-web.netlify.com/) because your browser might be displaying an older cached version.

I see you've added a button which only clears completed tasks, but I couldn't find the code which actually updates that subset of storage.

**Comment by AshtrayShetty** [comment]
It looked something like this (also the edit button was overlapped by the text, but idk what happened now):
Time Bend - Google Chrome 19-03-2020 23_26_48

After changing:
Time Bend - Google Chrome 19-03-2020 23_30_07

**Comment by neelkamath** [comment]
I had fixed the edit button overlapping with the text. Also, the second image shows the edit icon aligned to the left, rather than the center of the checkbox and action. Are you sure you're on the correct commit (i.e., did you pull in upstream changes on your fork)?

**Comment by AshtrayShetty** [comment]
Maybe. But even if that's the case the first image looks kind of (dirty) doesn't it? Like the duration box goes onto the next line and stuff.

**Comment by neelkamath** [comment]
As I said before, these issues are probably an incorrect state of your copy of the repo. I think you have a mixture of old code, your own code, and half-merged upstream changes. As per my knowledge, no commit to the `master` branch has ever caused it to look like this. Please verify that you're working on a valid tree.

**Comment by AshtrayShetty** [comment]
I guess you're right.

**Pull request closed without merging**
